version: "3.4"

services:
  api:
    image: ghcr.io/genesis-warehouse/lab2-3:main
    container_name: backend
    depends_on:
      - db
    expose:
      - 5000
    networks:
      - webapp
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: postgres
    networks:
      - webapp
    environment:
      PGPORT: 5432
      POSTGRES_DB: genesiswarehouse
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - "/var/run/postgres/postgres.sock:/var/run/postgres/postgres.sock"
      - "dbdata:/var/lib/postgresql/data"
    restart: unless-stopped

  client:
    image: vuejs
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    networks:
      - webapp
    restart: unless-stopped

  web:
    image: nginx:1.25.3
    container_name: nginx
    networks:
      - webapp
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    restart: unless-stopped

networks:
  webapp:
    driver: bridge

volumes:
  dbdata: